//
//  HomeInteractor.swift
//  themoviedb
//
//  Created by Daniel Roble on 3/5/19.
//  Copyright (c) 2019 Daniel Roble. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func displayUI(request: Home.UI.Request) /// Display movies order by top rated or popular. popular is default
    func displayActionSheet(request: Home.ActionSheet.Request) /// Display action sheet for choose filter by top rated or popular
    func refreshMovies(title: String) /// refresh current display for selection on action sheet
}

protocol HomeDataStore {}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    var presenter: HomePresentationLogic?
    var worker = HomeWorker(homeStore: homeStore())
    let orderByOptions = ["Popular", "Top rated"]

    func displayUI(request: Home.UI.Request) {
        worker.fetchMovie(order: request.order) { (movies) in
            let response = Home.UI.Response(movies: movies)
            self.presenter?.presentUI(response: response)
        }
    }

    func displayActionSheet(request: Home.ActionSheet.Request) {
        let response = Home.ActionSheet.Response(title: "Order by",
                                                 message: "Choose a filter",
                                                 options: orderByOptions)
        self.presenter?.presentActionSheet(response: response)
    }

    func refreshMovies(title: String) {
        displayUI(request: Home.UI.Request(order: orderBy(rawValue: title) ?? .popular))
    }
}
