//
//  HomePresenter.swift
//  themoviedb
//
//  Created by Daniel Roble on 3/5/19.
//  Copyright (c) 2019 Daniel Roble. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentUI(response: Home.UI.Response)
    func presentActionSheet(response: Home.ActionSheet.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?

    // MARK: Do something
    func presentUI(response: Home.UI.Response) {
        let viewModel = Home.UI.ViewModel(movies: response.movies)
        viewController?.displayUI(viewModel: viewModel)
    }

    func presentActionSheet(response: Home.ActionSheet.Response) {
        let viewModel = Home.ActionSheet.ViewModel(title: response.title,
                                                 message: response.message,
                                                 options: response.options)
        viewController?.displayActionSheet(viewModel: viewModel)
    }
}
