//
//  DetailMovieModels.swift
//  themoviedb
//
//  Created by Daniel Roble on 3/6/19.
//  Copyright (c) 2019 Daniel Roble. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailMovie {
    // MARK: Use cases

    enum UI {
        struct Request { }
        struct Response {
            let title: String
            let posterURL: URL
            let voteAverage: String
            let releaseDate: String
            let overview: String
        }
        struct ViewModel {
            let title: String
            let posterURL: URL
            let voteAverage: String
            let releaseDate: String
            let overview: String
        }
    }
}
