//
//  DetailMovieRouter.swift
//  themoviedb
//
//  Created by Daniel Roble on 3/6/19.
//  Copyright (c) 2019 Daniel Roble. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailMovieRoutingLogic {
    func routeToDismiss()
}

protocol DetailMovieDataPassing {
    var dataStore: DetailMovieDataStore? { set get }
}

class DetailMovieRouter: NSObject, DetailMovieRoutingLogic, DetailMovieDataPassing {
    weak var viewController: DetailMovieViewController?
    var dataStore: DetailMovieDataStore?

    func routeToDismiss() {
        viewController?.presentingViewController?.dismiss(animated: true, completion: nil)
    }
}
